---
title: "About Us"
subtitle: "*Columbia University Cardiothoracic Surgery Research Program*"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

# Our Team

## Primary Investigator 

 *Giovanni Ferrari, PhD*
 
* [Twitter](https://twitter.com/ferrag02)
* [Email](mailto:<gf2375@cumc.columbia.edu>)

Associate Professor of Surgical Sciences and Scientific Director of the Cardiothoracic Research Program at Columbia University. He has over 13 years experience in the field of cell biology and cardiovascular medicine. After his postdoctoral work at New York University he became faculty and group leader at University of Pennsylvania, first as Assistant, and later, as Associate Professor. At UPenn he launched the Penn Cardiac Bioregistry for the division of cardiovascular surgery. In 2017 he relocated his program to Columbia. Currently he is directing the Columbia Biobank for Translational Studies (CBTS), an applied human biobank and clinical database supporting translational and precision medicine initiatives. Dr. Ferrari maintains his role as principal investigator of the Penn Cardiac Bioregistry and Adjunct Associate Professor at UPenn.

Giovanni Ferrari, PhD\
Associate Professor\
Columbia University Department of Surgery\
Director, Cardiothoracic Surgery Research\
Director, Columbia Biobank for Translational Science (CBTS)\
Black Building – 650 W. 168th Street, 4th Floor Suite 4-443\
New York, NY 10032\
Office: (212) 305-8615\

\
				
### Associate Research Scientists

 *Esti Castillero, PhD*
 
 * [Twitter](https:twitter.com/esticastillero)



 *Chiara Camillo, PhD*

\

### Postdoctoral Research Fellows	

 *Yingfei Xue, PhD*

 *Antonio Frasca, PhD*

\

### Surgical Residents			

 *Alexey Abramov, MD*
 
*Dov Levine, MD*

*Clinton Erwin, MD*

*Michael Simpson, MD*

\

### Biobank			

 *Vivian Moreno*

\

### Lab Manager

 *Mangesh Kurade*

\

### Medical Students

 *Nicolo (U of Milan)*
 
 *Eduardo (U of Bologna)*
 
 *Ervin (Morehouse School of Medicine)*

\

### Biomedical Engineering Students		

*Mar Mas Martinez (Columbia University)*

\

### Alumni

Residents\
Postdocs