---
output: 
  html_document:
    toc: true
    toc_float: true
    includes:
      in_header: hero-image.html
editor_options: 
  chunk_output_type: console
---

<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

\

## <i class='fas fa-compass'></i> Our Lab

Welcome to the Ferrari Laboratory website.  We are located at the Columbia University Irving Medical Center in New York City, New York.

\

## <i class='fas fa-flask'></i> Our Research

Coming soon

\


## <i class='fas fa-rss-square'></i> Lab in the News

Coming soon

\

## <i class='fas fa-comments'></i> Social Media

<a class="twitter-timeline" data-width="650" data-height="350" href="https://twitter.com/lab_ferrari?ref_src=twsrc%5Etfw">Tweets by lab_ferrari</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

\

## <i class='fas fa-camera'></i> Photos 

Coming soon

\


##  <i class='fas fa-bookmark'></i> Navigate

\


### Ferrari Lab Links

\

<i class='fas fa-users'></i> [About Us](about.html)\
Meet our team

<i class='fas fa-flask'></i> [Projects and Publications](projects.html)\
Learn about our ongoing projects and publications

<i class='fas fa-vial'></i> [Cardiothoracic Biobank Inquiries](biobank.html)\
Resources for accessing our biobank

<i class='fas fa-cubes'></i> [Research Program for Residents](program.html)\
Integrated program for surgical residents interested in a career in translational science 

\

### Columbia University Links

\

<i class='fas fa-laptop'></i> [Ferrari Lab – Columbia Biobank for Translational Science](https://columbiasurgery.org/research/ferrari-lab)\
Columbia University website to learn about the lab

<i class='fas fa-hospital-symbol'></i> [Columbia Cardiac Surgery](https://columbiasurgery.org/heart)\
Access healthcare services from Columbia Cardiac Surgery 

<i class='fas fa-procedures'></i> [Columbia Surgery Residency Program](https://columbiasurgery.org/general-surgery-residency)\
Learn about the Columbia Surgery residency program

<i class='fas fa-stethoscope'></i> [Columbia Integrated Cardiothoracic Surgery Residency Program (I-6)](https://columbiasurgery.org/cardiothoracic-training)\
Learn about the Columbia Surgery Integrated Cardiothoracic residency program


\

</body>
